module.exports.descriptors = [
  "Hypnotic",
  "Beautiful",
  "Stunning",
  "Natural",
  "Coral",
  "Forest",
  "Ocean",
  "Mesmerizing",
  "Artful",
  "Charming",
  "Alluring",
  "Elegant",
  "Graceful",
  "Angelic",
  "Ravishing",
  "Grand",
  "Pleasing",
  "Wonderful",
  "Classy",
  "Exquisite",
  "Beguiling",
  "Captivating",
  "Enticing",
  "Innate",
  "Pure",
  "Native",
  "Brilliant",
  "Superb",
  "Grandiose",
  "Lavish",
];

module.exports.articles = [
  "Bracelet",
  "Earring",
  "Anklet",
  "Necklace",
  "Shirt",
];

module.exports.descriptions = [
  "This pin is bell-shaped.  It is made from purple beads.  It is designed in a style that evokes the 1970's",
  "This silver ring is shaped like a gift. It is designed in a style that evokes the 1960's.  It's accented with a large transparent dark turquoise cushion-cut.",
  "This bracelet consists of four strands of pale pink, vivid yellow, pale green, and white beads.  It is designed in a style evocative of Art Deco aesthetics.",
  "This narrow ring is copper.",
  "This necklace consists of four strands of pale purple beads.  It is designed in a style that evokes the 1960's.",
  "This brass bracelet is set with a huge translucent red, yellow, dark green, and white trilliant-cut gem.",
  "This silver ring is almond-shaped. It is designed in a style evocative of Gothic aesthetics.  It is accented with a large transparent bright purple briolette-cut",
  "This silver earring is a rosette. It is designed in a style that evokes the 1970's.",
  "This wooden ring is shaped like five balloons. It is purple in color.  It is designed in a style evocative of Medieval fashion.",
  "This silver ring is a pointed ovoid. It is designed in a style that evokes the 1940's.  It is accented with a large transparent bright green heart-cut gem.",
  "This narrow bracelet is silver. It is engraved with a lime.",
  "This gold pin is shaped like a drum. It is designed in a style that evokes the 1970's.  It is accented with a huge opaque pale pink octagon-cut gem",
  "This black, dark gray, and magenta pin is shaped like a star. It is designed in a fantasy style.",
  "This gold ring is a rosette. It is designed in a style evocative of Medieval fashion.  It is accented with an assortment of transparent dusty green gems.",
  "This silver pendant is pear-shaped. It is designed in a style that evokes the 1950's.  It is accented with an assortment of transparent dusty pink gems.",
  "This ring is sewn from bright purple leather.  It is designed in a style that evokes the 1980's.  It is engraved with a pony.",
  "This ring is woven from maroon straw.  It is designed in a style evocative of Rococo fashion.",
];
